/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import UIAbility from '@ohos.app.ability.UIAbility';
import AbilityDelegatorRegistry from '@ohos.app.ability.abilityDelegatorRegistry';
import { Hypium } from '@ohos/hypium';
import testsuite from '../test/List.test';
import window from '@ohos.window';
import Want from '@ohos.app.ability.Want';
import AbilityConstant from '@ohos.app.ability.AbilityConstant';
import common from '@ohos.app.ability.common';
import HiLog from '../../../main/ets/common/utils/HiLog';
import data from '../test/testData.json';

const TAG: string = 'TestAbility';

export default class TestAbility extends UIAbility {
  public static uiContext?: common.UIAbilityContext;

  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam) {
    TestAbility.uiContext = this.context;
    HiLog.info(TAG, 'TestAbility onCreate');
    let abilityDelegator: AbilityDelegatorRegistry.AbilityDelegator = AbilityDelegatorRegistry.getAbilityDelegator();
    let abilityArguments: AbilityDelegatorRegistry.AbilityDelegatorArgs = AbilityDelegatorRegistry.getArguments();

    HiLog.info(TAG, 'start run testcase!!!');
    Hypium.setData(data);
    Hypium.hypiumTest(abilityDelegator, abilityArguments, testsuite);
  }

  onDestroy() {
    HiLog.info(TAG, 'TestAbility onDestroy');
    TestAbility.uiContext = undefined;
  }

  onWindowStageCreate(windowStage: window.WindowStage) {
    HiLog.info(TAG, 'TestAbility onWindowStageCreate');
    windowStage.loadContent('testability/pages/Index', (err, data) => {
      if (err.code) {
        HiLog.error(TAG, 'Failed to load the content.');
        return;
      }
      HiLog.info(TAG, 'Succeeded in loading the content');
    });
  }

  onWindowStageDestroy() {
    HiLog.info(TAG, 'TestAbility onWindowStageDestroy.');
  }

  onForeground() {
    HiLog.info(TAG, 'TestAbility onForeground');
  }

  onBackground() {
    HiLog.info(TAG, 'TestAbility onBackground');
  }
}